Repository lumen-oss/rocks.nvim, pull requests merged in 2024-04, with the labels that each got.

#243 chore(master): release 2.20.0
  CHANGELOG.md
Labels: autorelease: pending

#246 chore: update flake.lock
  flake.lock
Labels: dependencies, automated

#249 chore(master): release 2.20.1
  CHANGELOG.md
Labels: autorelease: pending

#252 chore(master): release 2.20.2
  CHANGELOG.md
Labels: autorelease: pending

#254 chore(master): release 2.21.0
  CHANGELOG.md
Labels: autorelease: pending

#263 chore(master): release 2.21.1
  CHANGELOG.md
Labels: autorelease: pending

#268 ref(installer): use dynamic home path instead of hardcoding it in the post-installation instructions
  installer.lua
Labels: enhancement

#270 chore(master): release 2.21.2
  CHANGELOG.md
Labels: autorelease: pending

#273 chore(master): release 2.21.3
  CHANGELOG.md
Labels: autorelease: pending

#274 chore: update flake.lock
  flake.lock
  spec/adapter_spec.lua
Labels: dependencies, automated

#279 chore(master): release 2.22.0
  CHANGELOG.md
Labels: autorelease: pending

#282 chore(master): release 2.23.0
  CHANGELOG.md
Labels: autorelease: pending

#284 chore(master): release 2.24.0
  CHANGELOG.md
Labels: autorelease: pending

#286 chore: update flake.lock
  flake.lock
Labels: dependencies, automated

#285 feat: ensure plugin runtime paths are available before rocks initialises
  .github/resources/init-integration.lua
  .github/resources/install-colorscheme.lua
  .github/workflows/integration.yml
  lua/rocks/adapter.lua
  lua/rocks/fs.lua
  lua/rocks/operations/helpers.lua
  spec/fs_spec.lua
Labels: enhancement

#290 chore(master): release 2.25.0
  CHANGELOG.md
Labels: autorelease: pending

#298 chore(master): release 2.26.0
  CHANGELOG.md
Labels: autorelease: pending

#303 chore: update flake.lock
  flake.lock
  flake.nix
Labels: dependencies, automated
